#!/bin/bash
jupyter serverextension enable --py nbserverproxy --sys-prefix
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             # @jupyterlab/hub-extension \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet \
                             dask-labextension@0.2

#EOF
